import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'mario-bros-vanilla',
  description: 'Generated by Gelt Code'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body>{children}</body>
    </html>
  );
}
